### ISSUE TITLE
跪求ubuntu版本或者现有版本的修改方法！！！

### ISSUE THREAD

**Issue by zhh2005757** [ws1990/k8s-install#1]
跪求ubuntu版本或者现有版本的修改方法！！！

**Comment by ws1990** [comment]
不好意思哈，好久没上来了。
我没太明白你的意思，ubuntu的版本应该不影响吧，这个我没有试验过。如果想通过虚拟机进行搭建的话，个人建议使用vmware，virtualBox在搭建的时候会出现一些莫名其妙的问题。
